#!/bin/sh

set -e

echo "▶ PULLING SUBMODULES ━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-"
git submodule --quiet foreach '
    BRANCH=$(git remote show origin | sed -n "/HEAD branch/s/.* //p")

    echo
    echo "▶▶ $name @ origin/$BRANCH"

    git checkout --quiet $BRANCH
    OLDHASH=$(git rev-parse HEAD)
    git pull --quiet --recurse-submodules || :
    git --no-pager log --oneline $OLDHASH..HEAD
'

echo "▶ UPDATING HELP TAGS ━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-"
nvim -u NONE -N --headless -c "helptags ALL" -c "qa!"

echo "▶ UPDATING TREESITTER (manual step) -━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-━-"
echo ""
echo "Per https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#msvc,"
echo "  1. Open x64 Native Tools Command Prompt for VS 2019."
echo "  2. Run the command: nvim -c \"TSUpdate\"."
