#!/bin/sh

set -e

git submodule foreach '
    BRANCH=$(git config -f $toplevel/.gitmodules submodule."$path".branch || echo master)
    git checkout $BRANCH
'

git submodule foreach '
    git pull --recurse-submodules || :
'

git submodule foreach '
    git submodule update --init --recursive || :
'

# Update help tags.
nvim -u NONE -N --headless -c "helptags ALL" -c "qa!"
